# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mystagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mystagram
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SDWebImage'
  pod 'JGProgressHUD'
  pod 'RxOptional'
  pod 'Toaster'

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  
  target 'MystagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MystagramUITests' do
    # Pods for testing
  end

end
